name: Deploy to Homelab

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Tailscale
        uses: tailscale/github-action@v2
        with:
          hostname: Github-actions
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: SSH
        uses: ErenKrt/ssh-push@main
        with:
          host: homelab
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./"
          destination: "/home/me/sih"
          scripts: |
            echo hello
